title: Julia for HPC Tutorial
email: godoywf@ornl.gov

remote_theme: just-the-docs/just-the-docs
# use to test locally
#theme: just-the-docs

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Julia Info
    color: blue

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.1.0"
